name: muon-ssh
version: "2.4.0"
summary: Graphical SFTP client and terminal emulator with helpful utilities
description: |
  Muon is a graphical SSH client. It has a file browser,
  terminal emulator, resource/process manager, disk space analyzer, 
  text editor, log viewer, and lots of other helpful tools, 
  making it easy to work with remote servers.

  More information is available on GitHub Repo: https://github.com/devlinx9/muon-ssh
title: MuonSSH
website: https://github.com/devlinx9/muon-ssh
issues: https://github.com/devlinx9/muon-ssh/issues
grade: stable
base: core22
icon: snap/gui/muonssh.png
confinement: strict

compression: lzo

apps:
  muon-ssh:
    command: usr/bin/java -jar $SNAP/jar/muonssh_2.4.0.jar
    common-id: muonssh.desktop
    environment:
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
      JAVA_HOME: ${SNAP}/usr/lib/jvm/java-17-openjdk-amd64
      PATH: ${SNAP}/usr/bin:${JAVA_HOME}/bin:$PATH
    plugs: [x11, ssh-keys, network, desktop, home, network-bind]

parts:
  muon-ssh:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar/
      snapcraftctl build
      cp muon-app/target/muonssh*.jar $SNAPCRAFT_PART_INSTALL/jar/
    stage-packages:
      - openjdk-17-jre
      - x11-utils
    organize:
      usr/lib/jvm/java-17-openjdk-${SNAP_ARCH}/bin/java: usr/bin/java